import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export interface N9PdfData {
  tenantName: string;
  landlordName: string;
  rentalAddress: string;
  unitNumber: string | null;
  terminationDate: string;
  reason: string;
  signatureName: string;
  signatureDate: string;
  monthlyRent: string;
  leaseStartDate: string;
}

const MARGIN_LEFT = 50;
const MARGIN_RIGHT = 50;
const PAGE_TOP = 770;
const LINE_HEIGHT = 16;
const SECTION_GAP = 24;

export async function generateN9Pdf(data: N9PdfData): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // Letter size

  const fontRegular = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 612;
  const contentWidth = pageWidth - MARGIN_LEFT - MARGIN_RIGHT;
  let y = PAGE_TOP;

  function drawText(
    text: string,
    options: {
      font?: typeof fontRegular;
      size?: number;
      color?: ReturnType<typeof rgb>;
      x?: number;
      maxWidth?: number;
    } = {}
  ) {
    const font = options.font ?? fontRegular;
    const size = options.size ?? 10;
    const color = options.color ?? rgb(0, 0, 0);
    const x = options.x ?? MARGIN_LEFT;

    page.drawText(text, { x, y, size, font, color });
    y -= LINE_HEIGHT;
  }

  function drawWrappedText(
    text: string,
    options: {
      font?: typeof fontRegular;
      size?: number;
      maxWidth?: number;
    } = {}
  ) {
    const font = options.font ?? fontRegular;
    const size = options.size ?? 10;
    const maxWidth = options.maxWidth ?? contentWidth;

    const words = text.split(' ');
    let line = '';

    for (const word of words) {
      const test = line ? `${line} ${word}` : word;
      const width = font.widthOfTextAtSize(test, size);
      if (width > maxWidth && line) {
        drawText(line, { font, size });
        line = word;
      } else {
        line = test;
      }
    }
    if (line) {
      drawText(line, { font, size });
    }
  }

  function drawLine() {
    page.drawLine({
      start: { x: MARGIN_LEFT, y: y + 8 },
      end: { x: pageWidth - MARGIN_RIGHT, y: y + 8 },
      thickness: 0.5,
      color: rgb(0.7, 0.7, 0.7),
    });
    y -= 8;
  }

  function sectionGap() {
    y -= SECTION_GAP;
  }

  // Header
  drawText('FORM N9', { font: fontBold, size: 18 });
  y -= 4;
  drawText("Tenant's Notice to Terminate the Tenancy", { font: fontBold, size: 12 });
  y -= 2;
  drawText('Residential Tenancies Act, 2006', { size: 8, color: rgb(0.4, 0.4, 0.4) });
  sectionGap();
  drawLine();
  sectionGap();

  // Section 1: Addresses
  drawText('1. Address of the Rental Unit', { font: fontBold, size: 11 });
  y -= 4;
  const fullAddress = data.unitNumber
    ? `Unit ${data.unitNumber}, ${data.rentalAddress}`
    : data.rentalAddress;
  drawWrappedText(fullAddress);
  sectionGap();

  // Section 2: Landlord
  drawText('2. Landlord Name', { font: fontBold, size: 11 });
  y -= 4;
  drawText(data.landlordName);
  sectionGap();

  // Section 3: Tenant
  drawText('3. Tenant Name', { font: fontBold, size: 11 });
  y -= 4;
  drawText(data.tenantName);
  sectionGap();

  // Section 4: Lease details
  drawText('4. Tenancy Details', { font: fontBold, size: 11 });
  y -= 4;
  drawText(`Lease start date: ${data.leaseStartDate}`);
  drawText(`Monthly rent: ${data.monthlyRent}`);
  sectionGap();

  // Section 5: Termination
  drawText('5. Termination Date', { font: fontBold, size: 11 });
  y -= 4;
  drawText(`I want to terminate my tenancy on: ${data.terminationDate}`, { font: fontBold });
  sectionGap();

  // Section 6: Reason
  drawText('6. Reason for Termination', { font: fontBold, size: 11 });
  y -= 4;
  const reasonText =
    data.reason === 'end_of_term'
      ? 'End of fixed-term lease'
      : data.reason === 'moving_out'
        ? 'Moving out (periodic tenancy)'
        : 'Mutual agreement with landlord';
  drawText(reasonText);
  sectionGap();
  drawLine();
  sectionGap();

  // Signature block
  drawText('7. Signature', { font: fontBold, size: 11 });
  y -= 4;
  drawWrappedText(
    'I confirm that the information in this notice is true and that I am giving this notice ' +
      'in good faith. I understand that this notice terminates my tenancy on the date specified above.'
  );
  y -= 8;

  drawText(`Signed by: ${data.signatureName}`, { font: fontBold });
  drawText(`Date signed: ${data.signatureDate}`);
  sectionGap();
  drawLine();

  // Footer
  y -= 4;
  drawText(
    'This form was generated by ScrubHub in accordance with the Ontario Residential Tenancies Act, 2006.',
    { size: 7, color: rgb(0.5, 0.5, 0.5) }
  );
  drawText(
    'Landlord and Tenant Board (LTB) — Form N9: Tenant\'s Notice to Terminate the Tenancy.',
    { size: 7, color: rgb(0.5, 0.5, 0.5) }
  );

  return doc.save();
}
