'use client';

import { Separator } from '@/components/ui/separator';

interface N9PreviewProps {
  landlordName: string;
  tenantName: string;
  rentalAddress: string;
  terminationDate: string;
  phoneNumber: string;
  signatureFirstName: string;
  signatureLastName: string;
}

export function N9Preview({
  landlordName,
  tenantName,
  rentalAddress,
  terminationDate,
  phoneNumber,
  signatureFirstName,
  signatureLastName,
}: N9PreviewProps) {
  const formatted = new Date(terminationDate + 'T00:00:00').toLocaleDateString('en-CA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="rounded-lg border bg-card">
      <div className="border-b px-4 py-3">
        <p className="text-sm font-bold">FORM N9</p>
        <p className="text-xs text-muted-foreground">
          Tenant&apos;s Notice to End the Tenancy
        </p>
      </div>

      <div className="space-y-3 p-4 text-sm">
        <div className="grid grid-cols-2 gap-3">
          <Field label="To (Landlord)" value={landlordName} />
          <Field label="From (Tenant)" value={tenantName} />
        </div>
        <Separator />
        <Field label="Address of the Rental Unit" value={rentalAddress} />
        <Separator />
        <p className="text-xs text-muted-foreground italic">
          I am giving this notice because I want to move out of the rental unit.
        </p>
        <div>
          <p className="text-xs text-muted-foreground">The last day of my tenancy will be</p>
          <p className="text-base font-bold text-foreground">{formatted}</p>
          <p className="text-xs text-muted-foreground italic">This is the termination date.</p>
        </div>
        <Separator />
        <div className="grid grid-cols-2 gap-3">
          <Field label="First Name" value={signatureFirstName || '—'} />
          <Field label="Last Name" value={signatureLastName || '—'} />
        </div>
        <Field label="Phone Number" value={phoneNumber || '—'} />
      </div>

      <div className="border-t bg-muted/30 px-4 py-2">
        <p className="text-[11px] text-muted-foreground">
          Generated by ScrubHub per the Ontario Residential Tenancies Act, 2006.
        </p>
      </div>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="font-medium">{value}</p>
    </div>
  );
}
