'use client';

import type { Lease, N9Reason } from '@/types/database';
import { Separator } from '@/components/ui/separator';

const REASON_TEXT: Record<N9Reason, string> = {
  end_of_term: 'End of fixed-term lease',
  moving_out: 'Moving out (periodic tenancy)',
  mutual_agreement: 'Mutual agreement with landlord',
};

interface N9PreviewProps {
  lease: Lease;
  reason: N9Reason;
  terminationDate: string;
}

export function N9Preview({ lease, reason, terminationDate }: N9PreviewProps) {
  const formatted = new Date(terminationDate + 'T00:00:00').toLocaleDateString('en-CA', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="rounded-lg border bg-card">
      <div className="border-b px-4 py-3">
        <p className="text-sm font-bold">FORM N9</p>
        <p className="text-xs text-muted-foreground">
          Tenant&apos;s Notice to Terminate the Tenancy
        </p>
      </div>

      <div className="space-y-3 p-4 text-sm">
        <Row label="Lease ID" value={lease.id.slice(0, 8)} />
        <Separator />
        <Row label="Lease type" value={lease.lease_type === 'fixed_term' ? 'Fixed term' : 'Monthly'} />
        <Row label="Rental period" value={lease.rental_period === 'monthly' ? 'Monthly' : 'Weekly'} />
        <Row
          label="Monthly rent"
          value={`$${(lease.monthly_rent_cents / 100).toFixed(2)}`}
        />
        <Row
          label="Lease start"
          value={new Date(lease.start_date).toLocaleDateString()}
        />
        {lease.end_date && (
          <Row
            label="Lease end"
            value={new Date(lease.end_date).toLocaleDateString()}
          />
        )}
        <Separator />
        <Row label="Reason" value={REASON_TEXT[reason]} />
        <div>
          <p className="text-xs text-muted-foreground">Termination date</p>
          <p className="text-base font-bold text-foreground">{formatted}</p>
        </div>
      </div>

      <div className="border-t bg-muted/30 px-4 py-2">
        <p className="text-[11px] text-muted-foreground">
          Generated by ScrubHub per the Ontario Residential Tenancies Act, 2006.
        </p>
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-baseline justify-between gap-4">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-right font-medium">{value}</p>
    </div>
  );
}
