import type { ListingWithCoordinates } from './mock-coordinates';

/**
 * Mock housing listings placed near healthcare facilities.
 * These are view-only (cannot apply). Used to populate the map when real listings are sparse.
 */
export const MOCK_LISTINGS: (ListingWithCoordinates & { isMock: true })[] = [
  {
    id: 'mock-1',
    title: 'Downtown Condo Near Toronto General',
    description: 'Bright 1-bedroom condo steps from Toronto General Hospital. Ideal for healthcare workers on rotation.',
    address: '200 Elizabeth St, Toronto',
    price_cents: 245000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.6585,
    longitude: -79.3860,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 650,
    is_furnished: true,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['3 months', '6 months'],
    isMock: true,
  },
  {
    id: 'mock-2',
    title: 'Sunnybrook Adjacent Suite',
    description: 'Furnished 2-bed near Sunnybrook Health Sciences. Quiet residential area.',
    address: '1132 Leslie St, North York',
    price_cents: 320000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.7170,
    longitude: -79.3750,
    bedrooms: 2,
    bathrooms: 2,
    square_footage: 950,
    is_furnished: true,
    are_pets_allowed: true,
    images: null,
    lease_terms: ['6 months', '12 months'],
    isMock: true,
  },
  {
    id: 'mock-3',
    title: 'Mississauga Trillium Area',
    description: 'Modern apartment near Trillium Health Mississauga. Transit-friendly.',
    address: '100 City Centre Dr, Mississauga',
    price_cents: 210000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.5920,
    longitude: -79.6380,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 580,
    is_furnished: false,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['3 months', '6 months', '12 months'],
    isMock: true,
  },
  {
    id: 'mock-4',
    title: 'Brampton Civic Vicinity',
    description: 'Spacious 3-bed house near Brampton Civic Hospital. Parking included.',
    address: '45 Sandalwood Pkwy E, Brampton',
    price_cents: 380000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.7280,
    longitude: -79.7580,
    bedrooms: 3,
    bathrooms: 2,
    square_footage: 1400,
    is_furnished: false,
    are_pets_allowed: true,
    images: null,
    lease_terms: ['6 months', '12 months'],
    isMock: true,
  },
  {
    id: 'mock-5',
    title: 'Hamilton General Area',
    description: 'Walk to Hamilton Health Sciences. Furnished studio for short-term stays.',
    address: '123 Main St W, Hamilton',
    price_cents: 185000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.2570,
    longitude: -79.8720,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 450,
    is_furnished: true,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['1 month', '3 months'],
    isMock: true,
  },
  {
    id: 'mock-6',
    title: 'Kitchener Grand River Proximity',
    description: '2-bed near Grand River Hospital. Quiet neighbourhood.',
    address: '250 King St E, Kitchener',
    price_cents: 220000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.4530,
    longitude: -80.4880,
    bedrooms: 2,
    bathrooms: 1,
    square_footage: 850,
    is_furnished: true,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['3 months', '6 months'],
    isMock: true,
  },
  {
    id: 'mock-7',
    title: 'North York General Neighbourhood',
    description: '1-bed condo near North York General. Great for residents.',
    address: '4001 Leslie St, North York',
    price_cents: 265000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.7590,
    longitude: -79.4080,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 620,
    is_furnished: true,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['6 months', '12 months'],
    isMock: true,
  },
  {
    id: 'mock-8',
    title: 'Scarborough Health Network Area',
    description: 'Affordable 2-bed near Scarborough Health Network General.',
    address: '3050 Lawrence Ave E, Scarborough',
    price_cents: 195000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.7500,
    longitude: -79.2350,
    bedrooms: 2,
    bathrooms: 1,
    square_footage: 780,
    is_furnished: false,
    are_pets_allowed: true,
    images: null,
    lease_terms: ['6 months', '12 months'],
    isMock: true,
  },
  {
    id: 'mock-9',
    title: 'Oakville Trafalgar Memorial Zone',
    description: 'Luxury 2-bed near Oakville Trafalgar Memorial Hospital.',
    address: '1230 Trafalgar Rd, Oakville',
    price_cents: 340000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.4650,
    longitude: -79.7240,
    bedrooms: 2,
    bathrooms: 2,
    square_footage: 1100,
    is_furnished: true,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['3 months', '6 months', '12 months'],
    isMock: true,
  },
  {
    id: 'mock-10',
    title: 'Markham-Stouffville Hospital Area',
    description: 'New build 3-bed near Markham-Stouffville Hospital.',
    address: '381 Church St, Markham',
    price_cents: 395000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.8690,
    longitude: -79.2580,
    bedrooms: 3,
    bathrooms: 2,
    square_footage: 1500,
    is_furnished: false,
    are_pets_allowed: true,
    images: null,
    lease_terms: ['12 months'],
    isMock: true,
  },
  {
    id: 'mock-11',
    title: 'St. Michael\'s Hospital Walk-Up',
    description: 'Charming 1-bed near St. Michael\'s. Downtown core.',
    address: '30 Bond St, Toronto',
    price_cents: 255000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.6515,
    longitude: -79.3765,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 600,
    is_furnished: true,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['3 months', '6 months'],
    isMock: true,
  },
  {
    id: 'mock-12',
    title: 'Cambridge Memorial Vicinity',
    description: '2-bed near Cambridge Memorial Hospital. Family-friendly.',
    address: '700 Coronation Blvd, Cambridge',
    price_cents: 205000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.3700,
    longitude: -80.3100,
    bedrooms: 2,
    bathrooms: 1,
    square_footage: 900,
    is_furnished: false,
    are_pets_allowed: true,
    images: null,
    lease_terms: ['6 months', '12 months'],
    isMock: true,
  },
  {
    id: 'mock-13',
    title: 'Guelph General Proximity',
    description: 'Cozy 1-bed near Guelph General Hospital.',
    address: '100 Stone Rd W, Guelph',
    price_cents: 195000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.5440,
    longitude: -80.2490,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 550,
    is_furnished: true,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['3 months', '6 months'],
    isMock: true,
  },
  {
    id: 'mock-14',
    title: 'SickKids Adjacent Studio',
    description: 'Compact studio for healthcare workers at SickKids.',
    address: '555 University Ave, Toronto',
    price_cents: 225000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.6550,
    longitude: -79.3890,
    bedrooms: 1,
    bathrooms: 1,
    square_footage: 420,
    is_furnished: true,
    are_pets_allowed: false,
    images: null,
    lease_terms: ['1 month', '3 months'],
    isMock: true,
  },
  {
    id: 'mock-15',
    title: 'Burlington Joseph Brant Area',
    description: '2-bed townhouse near Joseph Brant Hospital.',
    address: '1234 New St, Burlington',
    price_cents: 285000,
    status: 'published',
    created_at: new Date().toISOString(),
    latitude: 43.3260,
    longitude: -79.8030,
    bedrooms: 2,
    bathrooms: 2,
    square_footage: 1050,
    is_furnished: false,
    are_pets_allowed: true,
    images: null,
    lease_terms: ['6 months', '12 months'],
    isMock: true,
  },
];
